### ISSUE TITLE
Sunset/sunrise times

### ISSUE THREAD

**Issue by forbesye** [Green-Squad/AT-Forecast#8]
Would y'all be able to add sunset/sunrise times? I figure it wouldn't be too hard to pull it somewhere given the long/lat of each shelter.

Thanks!

**Comment by jordan-r-smith** [comment]
Hey! I've been pretty busy with work and things that I haven't really had the time to work on this project until recently. I just updated the Android app and I included the sunrise and sunset times on there. I haven't yet done it for the website because I'm working on a rewrite for it, but I'll be sure that it's included there also. Thanks for the suggestion! :)
